### ISSUE TITLE
생성되는 README의 뱃지 간격 조정

### ISSUE THREAD

**Issue by JungWinter** [Rainist/python#25]
![image](https://user-images.githubusercontent.com/13811604/53316523-9b091d00-390b-11e9-8e54-4e16ae0e1ad1.png)

위 처럼 생성되는데 뱃지 간격이 너무 좁아 이쁘지 않음
본래 템플릿에 화이트 스페이스를 넣어봤으나 템플릿 생성시 화이트스페이스가 제거되어 생성되는 문제때문에 보류했었음.

## As is

[![Python Version: 3.7](https://badgen.net/badge/python/3.7/blue)](https://docs.python.org/3.7/)[![Code Style: Black](https://badgen.net/badge/code%20style/black/black)](https://github.com/ambv/black)[![Build Status](https://badgen.net/badge/travis/passing/green)](https://travis-ci.com/)[![codecov](https://badgen.net/badge/coverage/100%25/green)](https://codecov.io/)

## To be

[![Python Version: 3.7](https://badgen.net/badge/python/3.7/blue)](https://docs.python.org/3.7/) [![Code Style: Black](https://badgen.net/badge/code%20style/black/black)](https://github.com/ambv/black) [![Build Status](https://badgen.net/badge/travis/passing/green)](https://travis-ci.com/) [![codecov](https://badgen.net/badge/coverage/100%25/green)](https://codecov.io/)

**Comment by AhnSeongHyun** [comment]
이래서 이슈를 확인해야하는군요.. PR을 날리려 봤더니 이미 있네요 ㅎㅎ

**Comment by kanziw** [comment]
원하는 스페이스 만큼 `&nbsp;` 를 뱃지 사이에 넣어보세요~ README.md 에서 테스트해보진 않았지만 여기에선 동작하네요~

### Before
[![Build Status](https://travis-ci.org/Rainist/python.svg?branch=master)](https://travis-ci.org/Rainist/python) [![Build Status](https://travis-ci.org/Rainist/python.svg?branch=master)](https://travis-ci.org/Rainist/python)

### After
[![Build Status](https://travis-ci.org/Rainist/python.svg?branch=master)](https://travis-ci.org/Rainist/python) &nbsp;&nbsp;&nbsp; [![Build Status](https://travis-ci.org/Rainist/python.svg?branch=master)](https://travis-ci.org/Rainist/python)
