### ISSUE TITLE
Dockerfile 생성여부 추가 

### ISSUE THREAD

**Issue by AhnSeongHyun** [Rainist/python#27]
docker 를 사용할 수 없는 환경에서는 불필요해서 
Dockerfile 생성을 선택할 수 있으면 좋을것 같네요

**Comment by JungWinter** [comment]
일단 생성한다음 `Dockerfile` 만 제거해주는걸로도 충분하지 않을까요?

**Comment by AhnSeongHyun** [comment]
이미 그렇게 하고있는데 ㅠㅠ 넘 귀찮음.. 😇

**Comment by JungWinter** [comment]
You can PR this
